# Generated by Django 5.0.7 on 2024-08-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_job_application_jobcategory_job_category_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
    ]
